name: Run Python Script every 2 hours

on:
  schedule:
    - cron: "0 */2 * * *"   # chạy mỗi 2 tiếng (UTC)
  workflow_dispatch:        # có nút Run workflow để test ngay

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run script
        run: |
          python script.py
