name: Telegram Debug Test

on:
  workflow_dispatch:  # Chỉ chạy thủ công

jobs:
  telegram-debug:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Chỉ 5 phút
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv
        
    - name: Create .env file
      run: |
        echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" > .env
        echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env
        
    - name: Test network connectivity
      run: |
        echo "Testing network connectivity..."
        curl -I https://api.telegram.org
        curl -I https://httpbin.org/get
        
    - name: Test Telegram API
      run: |
        python test_telegram_only.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
