name: Test Dependencies

on:
  workflow_dispatch:  # Chỉ chạy thủ công

jobs:
  test-deps:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        
    - name: Test imports
      run: |
        python -c "
        print('Testing imports...')
        
        # Test basic imports
        import ccxt
        print('✅ ccxt imported')
        
        import numpy as np
        print('✅ numpy imported')
        
        import pandas as pd
        print('✅ pandas imported')
        
        import requests
        print('✅ requests imported')
        
        from dotenv import load_dotenv
        print('✅ python-dotenv imported')
        
        import yfinance as yf
        print('✅ yfinance imported')
        
        from tradingview_ta import TA_Handler
        print('✅ tradingview-ta imported')
        
        import ta
        print('✅ ta imported')
        
        # Test ML imports
        from sklearn.ensemble import RandomForestClassifier
        print('✅ scikit-learn imported')
        
        import xgboost as xgb
        print('✅ xgboost imported')
        
        import lightgbm as lgb
        print('✅ lightgbm imported')
        
        import joblib
        print('✅ joblib imported')
        
        print('🎉 All dependencies imported successfully!')
        "
        
    - name: Test script import
      run: |
        python -c "
        print('Testing script.py imports...')
        exec(open('script.py').read())
        print('✅ script.py can be imported successfully!')
        "
